name = "aa-bot-pages"
compatibility_date = "2026-07-01"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "LEADS"
id = "e52151440e8f46818392747fe24b0224"
preview_id = "7961d16c73f7424f8062c73efea2b33b"
